Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Layout/EndAlignment:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/IndentationWidth:
  Enabled: false
Layout/MultilineOperationIndentation:
  Exclude:
    - 'bin/bundle'
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true


Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/Documentation:
  Exclude:
    - 'db/migrate/**'
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
Style/ExponentialNotation:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names
  Exclude:
    - 'bin/bundle'
Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'bin/bundle'
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 200
  Exclude:
    - 'bin/bundle'
